FROM python:3.10-slim

WORKDIR /app

COPY requirements .

RUN apt-get update && apt-get install -y python3-pip && pip3 install --no-cache-dir -r requirements

COPY ex_09_api_server.py .

CMD ["python3", "ex_09_api_server.py"]