
services:
  ollama:
    build:
      context: .
      dockerfile: dockerfile.ollama
    container_name: myollama
    ports:
      - "11434:11434"

  api:
    build:
      context: .
      dockerfile: dockerfile.server
    container_name: flask_api
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate
    ports:
      - "5001:5001"

  client:
    build:
      context: .
      dockerfile: dockerfile.client  
    container_name: flask_client
    depends_on:
      - api
    environment:
      - SERVER_URL=http://api:5001
    ports:
      - "5002:5002"